config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  namespace :admin do
    get 'fetch' => 'movies#fetch', as: 'fetch'
    resources :movies, :people, :lists, :users
    root 'dashboard#index'
  end

  namespace :api do
    resources :movies, only: [:index, :show] do
      with_options only: :index do |list_only|
        list_only.resources :alternative_titles
        list_only.resources :credits
        list_only.resources :critic_reviews
        list_only.resources :genres
        list_only.resources :keywords
        list_only.resources :posters
        list_only.resources :recommended_movies
        list_only.resources :releases
        list_only.resources :trivia
      end
    end

    resources :people, only: :show do
      resources :movie_credits, only: :index
    end

    resources :genres, only: [:index, :show] do
      resources :movies, only: :index
    end

    resources :keywords, only: [:index, :show] do
      resources :movies, only: :index
    end

    resources :users do
      resources :lists, only: :show
    end

    resources :lists do
      post 'toggle', on: :member
    end
  end

  resources :movies, only: [:index, :show]
  resources :users, only: [:new, :create, :edit, :update]
  resources :sessions, only: [:new, :create, :destroy]

  get 'watchlist' => 'lists#show', id: 'watchlist', as: :watchlist
  get 'watched'   => 'lists#show', id: 'watched', as: :watched
  get 'favorites' => 'lists#show', id: 'favorites', as: :favorites

  get 'sign-in' => 'sessions#new', as: :signin
  delete 'sign-out' => 'sessions#destroy', as: :signout
  get 'join' => 'users#new', as: :join

  post 'oauth/callback' => 'oauths#callback'
  get 'oauth/callback' => 'oauths#callback'
  get 'oauth/:provider' => 'oauths#oauth',  as: :auth_at_provider

  get 'profile' => 'users#edit', as: :profile
  post 'profile' => 'users#update'

  mount Sidekiq::Web, at: '/sidekiq'

  root 'movies#index'
end

app/controllers/admin/movies_controller.rb
class Admin::MoviesController < AdminController
  def index
    @movies = Movie.with_title.paginate(page: params[:page], per_page: 72).order('released_on DESC')
    @movie_count = @movies.count
  end

  def show
    @movie = Movie.friendly.find(params[:id])
    @directors = @movie.directorships.limit(3)
    @writers = @movie.writerships.limit(3)
    @actors = @movie.actorships.limit(15)
  end

  def fetch
    Movie.fetch params[:imdb_id]
    redirect_to admin_root_path
  end
end

app/controllers/api/movies_controller.rb
module API
  class MoviesController < APIController
    # GET /movies
    # GET /genres/:genre_id/movies
    # GET /keywords/:keyword_id/movies
    def index
      if genre_id = params[:genre_id]
        @movies = Genre.find(genre_id).movies
      elsif keyword_id = params[:keyword_id]
        @movies = Keyword.find(keyword_id).movies
      else
        @movies = Movie.all
      end

      if decade = params[:decade]
        @movies = @movies.where year: get_years_by_decade(decade)
      end

      if year = params[:year]
        @movies = @movies.where year: year
      end

      @movies.paginate page: params[:page]
    end

    # GET /movies/:id
    def show
      @movie = Movie.find params[:id]
      @primary_poster = @movie.primary_poster
      @directors = @movie.directors
      @starred_actors = @movie.stars
    end

    private

    def get_years_by_decade(decade)
      decade = decade.to_i
      (decade..decade + 9)
    end
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def index
    find_user_lists
    @movies = Movie.with_title.released.with_pop_index
              .includes(:genres)
              .includes(:primary_poster)
              .order('pop_index')
              .paginate(page: params[:page], per_page: 42)
  end

  def show
    find_user_lists
    @movie = Movie.friendly.find(params[:id])
    @title = @movie.title
    @trailer = @movie.trailers.first
    @recommended_movies = @movie.recommended_movies.with_title
                          .includes(:genres)
                          .includes(:primary_poster)
  end
end

app/views/movies/_cast_and_crew.html.haml
%dl.dl-inline
  %dt Cast:
  %dd.text-muted
    = @movie.stars.map(&:name).join(', ')
%dl.dl-inline
  %dt Directed by:
  %dd.text-muted
    = @movie.directors.uniq.map(&:name).join(', ')
%dl.dl-inline
  %dt Written by:
  %dd.text-muted
    = @movie.writers.uniq.map(&:name).join(', ')
%dl.dl-inline.hidden-xs
  %dt Produced by:
  %dd.text-muted
    = @movie.producers.uniq.map(&:name).join(', ')

app/views/movies/_list_toggler.html.haml
- size = options[:size] || :sm
- btn_block = 'btn-block' if options[:block_buttons]
- watchlist_class = @watchlist_movies.include?(movie.id) ? 'btn-on' : ''
- watched_class = @watched_movies.include?(movie.id) ? 'btn-on' : ''
- favorites_class = @favorite_movies.include?(movie.id) ? 'btn-on' : ''
.list-toggler{ data: { movie_id: movie.id } }
  = content_tag :span, nil, class: "btn btn-#{size} btn-default #{btn_block} #{watchlist_class}", id: 'watchlist', data: { list_id: @watchlist.id } do
    = fa_icon 'star', text: 'Watchlist'
  = content_tag :span, nil, class: "btn btn-#{size} btn-default #{btn_block} #{watched_class}", id: 'watched', data: { list_id: @watched.id } do
    = fa_icon 'check-square-o', text: 'Watched'
  - if options[:show_favorites]
    = content_tag :span, nil, class: "btn btn-#{size} btn-default #{btn_block} #{favorites_class}", id: 'favorites', data: { list_id: @favorites.id } do
      = fa_icon 'heart', text: 'Favorites'

app/views/movies/_movie.html.haml
- if @watched_movies.include?(movie.id)
  - thumbnail_class = 'poster-watched'
  - watched_class = 'btn-on'
- if @watchlist_movies.include?(movie.id)
  - thumbnail_class = 'poster-watchlist'
  - watchlist_class = 'btn-on'

.col-xs-4.col-sm-3.col-md-3.col-lg-2
  .thumbnail.thumbnail-poster{class: thumbnail_class, id: "thumbnail-poster-#{movie.id}"}
    = link_to movie_path(movie) do
      = poster_image_for movie, :md, alt: "#{movie.title} (#{movie.year})"
      .caption.hidden-xs
        %h2= movie.title
        - if movie.year
          %p= movie.year
        - if movie.genres
          %ul.list-inline
            - movie.genres.each do |genre|
              %li.small= genre.name
        = render partial: 'movies/list_toggler', locals: { movie: movie, options: { block_buttons: true } }

app/views/movies/_pagination.html.haml
.col-xs-12
  = will_paginate @movies, renderer: BootstrapPagination::Rails

app/views/movies/_ratings_inline.html.haml
%ul.media-list.ratings-list.list-inline
  - if @movie.imdb_rating
    %li.media
      %span.media-left
        = rating_image('imdb', @movie.imdb_rating, imdb_rating_count(@movie.imdb_rating_count), '25x25')
      .media-body
        .score
          = @movie.imdb_rating
          %small.text-muted.hidden-xs /10
  - if @movie.rotten_critics_rating && @movie.rotten_critics_rating > 0
    %li.media
      %span.media-left
        = rating_image('rt_critics', @movie.rotten_critics_rating, 'RottenTomatoes critics', '25x25')
      .media-body
        .score= "#{@movie.rotten_critics_rating}%"
  - if @movie.rotten_audience_rating
    %li.media
      %span.media-left
        = rating_image('rt_audience', @movie.rotten_audience_rating, 'RottenTomatoes audience', '25x25')
      .media-body
        .score= "#{@movie.rotten_audience_rating}%"
  - if @movie.metacritic_rating
    %li.media.hidden-xs.hidden-sm
      %span.media-left
        = rating_image('metacritic', @movie.metacritic_rating, 'MetaCritic', '25x25')
      .media-body
        .score= "#{@movie.metacritic_rating}%"

app/views/movies/_recommended_movie.html.haml
- thumbnail_class = 'poster-watched' if @watched_movies.include?(movie.id)
- thumbnail_class = 'poster-watchlist' if @watchlist_movies.include?(movie.id)

.col-xs-12
  %hr
  .row
    %li.media.recommended-movie
      .col-xs-3
        .thumbnail.thumbnail-poster{class: thumbnail_class, id: "thumbnail-poster-#{movie.id}"}
          = link_to movie_path(movie) do
            = poster_image_for movie, :sm, alt: "#{movie.title} (#{movie.year})"
      .col-xs-9
        .media-body
          %h4.movie-title
            = link_to movie.title, movie_path(movie)
          %ul.list-inline.list-meta.text-muted
            - if movie.year
              %li= movie.year
            - if movie.genres
              %li
                = movie.genres.pluck(:name).join(' &middot; ').html_safe
          %p= movie.description

          = render partial: 'list_toggler', locals: { movie: movie, options: { size: :sm, show_favorites: true } }

app/views/movies/index.html.haml
.container-fluid
  %h1 Popular Movies
  .row.movie-grid
    = render @movies
  .row
    = render 'pagination'

app/views/movies/show.html.haml
- if @watched_movies.include?(@movie.id)
  - thumbnail_class = 'poster-watched'
  - watched_class = 'btn-on'
- if @watchlist_movies.include?(@movie.id)
  - thumbnail_class = 'poster-watchlist'
  - watchlist_class = 'btn-on'

= backdrop_for @movie
.container-fluid#wrapper
  .row
    .col-sm-3.left-column
      .thumbnail.thumbnail-poster.hidden-xs{class: thumbnail_class, id: "thumbnail-poster-#{@movie.id}"}
        = poster_image_for @movie, :lg, alt: "#{@movie.title} (#{@movie.year})"
      = render partial: 'list_toggler', locals: { movie: @movie, options: { size: :lg, show_favorites: true, block_buttons: true } }
    .col-sm-6.center-column
      %h1.movie-title
        = @movie.title
      %ul.list-inline.list-meta.text-muted
        - if @movie.year
          %li= @movie.year
        - if @movie.genres
          %li
            = @movie.genres.pluck(:name).join(' &middot; ').html_safe

      = render partial: 'ratings_inline'

      %p.lead= @movie.description

      = render partial: 'cast_and_crew'

      - unless @recommended_movies.empty?
        %h3 Recommended movies
        .row
          %ul.media-list
            = render partial: 'recommended_movie', collection: @recommended_movies, as: :movie
    .col-sm-3
      - if @movie.released_on
        %dl
          %dt Release date
          %dd.text-muted
            = fa_icon 'calendar', text: @movie.released_on.strftime('%e %B %Y')
      - if @movie.runtime
        %dl
          %dt Runtime
          %dd.text-muted
            = fa_icon 'clock-o', text: format_runtime(@movie.runtime)
      - if @movie.mpaa_rating
        %dl
          %dt MPAA rating
          %dd.text-muted
            = fa_icon 'ticket', text: @movie.mpaa_rating
      - if @movie.countries
        %dl
          %dt Countries
          %dd.text-muted
            = fa_icon 'globe', text: @movie.countries.map(&:name).join(', ')
      - if @movie.languages
        %dl
          %dt Languages
          %dd.text-muted
            = fa_icon 'comments-o', text: @movie.languages.map(&:name).join(', ')
      - if @movie.keywords.present?
        %dl.keywords.hidden-xs
          %dt
            Keywords
            %span.keywords-expander
              = link_to fa_icon('angle-down'), '#'
          %dd.text-muted
            %ul.list-inline
              - @movie.keywords.each do |kw|
                = content_tag :li, class: 'label-keyword' do
                  = fa_icon 'tag', text: kw.name
= sublime_video @trailer.youtube_id if @trailer