config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  namespace :admin do
    get 'fetch' => 'movies#fetch', as: 'fetch'
    resources :movies, :people, :lists, :users
    root 'dashboard#index'
  end

  namespace :api do
    resources :movies, only: [:index, :show] do
      with_options only: :index do |list_only|
        list_only.resources :alternative_titles
        list_only.resources :credits
        list_only.resources :critic_reviews
        list_only.resources :genres
        list_only.resources :keywords
        list_only.resources :posters
        list_only.resources :recommended_movies
        list_only.resources :releases
        list_only.resources :trivia
      end
    end

    resources :people, only: :show do
      resources :movie_credits, only: :index
    end

    resources :genres, only: [:index, :show] do
      resources :movies, only: :index
    end

    resources :keywords, only: [:index, :show] do
      resources :movies, only: :index
    end

    resources :users do
      resources :lists, only: :show
    end

    resources :lists do
      post 'toggle', on: :member
    end
  end

  resources :movies, only: [:index, :show]
  resources :users, only: [:new, :create, :edit, :update]
  resources :sessions, only: [:new, :create, :destroy]

  get 'watchlist' => 'lists#show', id: 'watchlist', as: :watchlist
  get 'watched'   => 'lists#show', id: 'watched', as: :watched
  get 'favorites' => 'lists#show', id: 'favorites', as: :favorites

  get 'sign-in' => 'sessions#new', as: :signin
  delete 'sign-out' => 'sessions#destroy', as: :signout
  get 'join' => 'users#new', as: :join

  post 'oauth/callback' => 'oauths#callback'
  get 'oauth/callback' => 'oauths#callback'
  get 'oauth/:provider' => 'oauths#oauth',  as: :auth_at_provider

  get 'profile' => 'users#edit', as: :profile
  post 'profile' => 'users#update'

  mount Sidekiq::Web, at: '/sidekiq'

  root 'movies#index'
end

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < AdminController
  def index
    @title = 'Dashboard'
  end
end

app/views/admin/dashboard/index.html.haml
.row
  .col-xs-12.col-sm-6.col-md-3
    = form_tag admin_fetch_path, method: :get, class: 'admin-search-form' do
      .input-group
        %input.form-control#imdb_id{placeholder: 'IMDb ID', type: 'text', name: 'imdb_id'}/
        %span.input-group-btn
          %button.btn.btn-default{type: 'submit'}
            = fa_icon 'plus-circle'
.row
  .col-xs-12.col-sm-6.col-md-3
    %form.admin-search-form{role: 'form'}
      .input-group
        %input.form-control{placeholder: 'Search movies', type: 'text'}/
        %span.input-group-btn
          %button.btn.btn-default{type: 'submit'}
            = fa_icon 'search'
    .panel.panel-primary
      .panel-heading
        %h3.panel-title
          = fa_icon('film')
          = link_to admin_movies_path do
            %span.badge.pull-right 385
            Movies
      .list-group
        = link_to '#', {class: 'list-group-item'} do
          %span.badge 367
          Fetched
        = link_to '#', {class: 'list-group-item'} do
          %span.badge 18
          Unfetched
    %hr.visible-xs.visible-sm/
  .col-xs-12.col-sm-6.col-md-3
    %form.admin-search-form{role: 'form'}
      .input-group
        %input.form-control{placeholder: 'Search people', type: 'text'}/
        %span.input-group-btn
          %button.btn.btn-default{type: 'submit'}
            = fa_icon 'search'
    .panel.panel-primary
      .panel-heading
        %h3.panel-title
          = fa_icon('users')
          = link_to admin_people_path do
            %span.badge.pull-right 12637
            People
      .list-group
        = link_to '#', {class: 'list-group-item'} do
          %span.badge 327
          Fetched
        = link_to '#', {class: 'list-group-item'} do
          %span.badge 12310
          Unfetched
    %hr.visible-xs.visible-sm/
  .col-xs-12.col-sm-6.col-md-3
    %form.admin-search-form{role: 'form'}
      .input-group
        %input.form-control{placeholder: 'Search lists', type: 'text'}/
        %span.input-group-btn
          %button.btn.btn-default{type: 'submit'}
            = fa_icon 'search'
    .panel.panel-primary
      .panel-heading
        %h3.panel-title
          = fa_icon('list')
          = link_to admin_lists_path do
            Lists
      .list-group
        = link_to '#', {class: 'list-group-item'} do
          System lists
        = link_to '#', {class: 'list-group-item'} do
          Fetch from IMDb
    %hr.visible-xs/
  .col-xs-12.col-sm-6.col-md-3
    %form.admin-search-form{role: 'form'}
      .input-group
        %input.form-control{placeholder: 'Search users', type: 'text'}/
        %span.input-group-btn
          %button.btn.btn-default{type: 'submit'}
            = fa_icon 'search'
    .panel.panel-primary
      .panel-heading
        %h3.panel-title
          = fa_icon('users')
          = link_to admin_users_path do
            %span.badge.pull-right 95
            Users
      .list-group
        = link_to '#', {class: 'list-group-item'} do
          %span.badge 18
          Online
        = link_to '#', {class: 'list-group-item'} do
          Recent