config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  namespace :admin do
    get 'fetch' => 'movies#fetch', as: 'fetch'
    resources :movies, :people, :lists, :users
    root 'dashboard#index'
  end

  namespace :api do
    resources :movies, only: [:index, :show] do
      with_options only: :index do |list_only|
        list_only.resources :alternative_titles
        list_only.resources :credits
        list_only.resources :critic_reviews
        list_only.resources :genres
        list_only.resources :keywords
        list_only.resources :posters
        list_only.resources :recommended_movies
        list_only.resources :releases
        list_only.resources :trivia
      end
    end

    resources :people, only: :show do
      resources :movie_credits, only: :index
    end

    resources :genres, only: [:index, :show] do
      resources :movies, only: :index
    end

    resources :keywords, only: [:index, :show] do
      resources :movies, only: :index
    end

    resources :users do
      resources :lists, only: :show
    end

    resources :lists do
      post 'toggle', on: :member
    end
  end

  resources :movies, only: [:index, :show]
  resources :users, only: [:new, :create, :edit, :update]
  resources :sessions, only: [:new, :create, :destroy]

  get 'watchlist' => 'lists#show', id: 'watchlist', as: :watchlist
  get 'watched'   => 'lists#show', id: 'watched', as: :watched
  get 'favorites' => 'lists#show', id: 'favorites', as: :favorites

  get 'sign-in' => 'sessions#new', as: :signin
  delete 'sign-out' => 'sessions#destroy', as: :signout
  get 'join' => 'users#new', as: :join

  post 'oauth/callback' => 'oauths#callback'
  get 'oauth/callback' => 'oauths#callback'
  get 'oauth/:provider' => 'oauths#oauth',  as: :auth_at_provider

  get 'profile' => 'users#edit', as: :profile
  post 'profile' => 'users#update'

  mount Sidekiq::Web, at: '/sidekiq'

  root 'movies#index'
end

app/models/user.rb
class User < ActiveRecord::Base
  include FriendlyId
  friendly_id :username

  authenticates_with_sorcery!

  validates :username,
            format: {
              with: /\A[a-z0-9]+\z/i,
              message: 'can only contain digits 0-9 and letters A-Z.'
            },
            length: {
              in: 2..20, message: 'must be 2 to 20 characters'
            },
            uniqueness: {
              case_sensitive: false,
              message: 'is already taken. Choose another.'
            },
            allow_blank: true

  validates :email,
            format: { with: /\A.+@.+\..+\z/i, message: 'is invalid' },
            uniqueness: {
              case_sensitive: false,
              message: 'is already taken. Choose another.'
            },
            allow_blank: true
  validates :password,
            length: { minimum: 5, message: 'must be minimum 5 characters' },
            allow_blank: true

  has_many :lists, dependent: :destroy

  has_one :auth_token, dependent: :destroy

  has_many :authentications, dependent: :destroy
  accepts_nested_attributes_for :authentications

  before_create :set_auth_token
  before_create :ensure_username_unique
  before_save :ensure_username_present
  after_create :set_uuid
  after_create :create_default_user_lists, unless: Proc.new { |u| u.system_user? }

  def self.system
    User.find_by(username: 'flickflow')
  end

  def self.generate_username
    prefix = 'user'
    loop do
      username = "#{prefix}#{SecureRandom.random_number(1_000_000)}"
      break username unless User.exists? username: username
    end
  end

  def create_default_user_lists
    lists.movie.create name: 'Watchlist'
    lists.movie.create name: 'Watched'
    lists.movie.create name: 'Favorites'
    lists.person.create name: 'Favorite People'
  end

  def system_user?
    self == User.system
  end

  def should_generate_new_friendly_id?
    username_changed? || super
  end

  def api_token
    auth_token.token
  end

  private

  def ensure_username_unique
    return unless User.exists? username: username
    prefix = username
    suffix = 0
    loop do
      self.username = "#{prefix}#{suffix + 1}"
      break unless User.exists? username: username
    end
  end

  def ensure_username_present
    self.username = User.generate_username if username.blank?
  end

  def set_auth_token
    return if auth_token.present?
    self.auth_token = AuthToken.create(token: AuthToken.generate)
  end

  def set_uuid
    update(uuid: SecureRandom.uuid)
  end
end

# == Schema Information
#
# Table name: users
#
#  id                              :integer          not null, primary key
#  name                            :string
#  username                        :string
#  email                           :string
#  crypted_password                :string
#  salt                            :string
#  slug                            :string
#  uuid                            :uuid
#  created_at                      :datetime
#  updated_at                      :datetime
#  remember_me_token               :string
#  remember_me_token_expires_at    :datetime
#  reset_password_token            :string
#  reset_password_token_expires_at :datetime
#  reset_password_email_sent_at    :datetime
#  last_login_at                   :datetime
#  last_logout_at                  :datetime
#  last_activity_at                :datetime
#  last_login_from_ip_address      :string
#
# Indexes
#
#  index_users_on_email                                (email)
#  index_users_on_last_logout_at_and_last_activity_at  (last_logout_at,last_activity_at)
#  index_users_on_remember_me_token                    (remember_me_token)
#  index_users_on_reset_password_token                 (reset_password_token)
#  index_users_on_slug                                 (slug) UNIQUE
#  index_users_on_username                             (username) UNIQUE
#

app/controllers/users_controller.rb
class UsersController < ApplicationController
  layout 'pages'
  skip_before_action :require_login, only: [:new, :create]
  skip_before_action :redirect_to_profile, only: [:edit, :update]

  def new
    @user = User.new
    @title = 'Join'
  end

  def create
    @user = User.new user_params

    if @user.save
      auto_login @user
      redirect_to root_path, flash: { success: "Alright! You've successfully created your profile on flickflow. Now go discover some good movies and add them to your Watchlist." }
    else
      @title = 'Join'
      render action: :new
    end
  end

  def edit
    @user = current_user
    password_label_for @user
    @title = 'Your Profile'
    render layout: 'application'
  end

  def update
    @user = current_user

    if @user.update user_params
      redirect_to root_path,
                  flash: { success: 'Your profile was successfully updated.' }
    else
      password_label_for @user
      @title = 'Your Profile'
      render action: :edit, layout: 'application'
    end
  end

  private

  def user_params
    params.require(:user)
      .permit(:name, :username, :email, :password)
  end

  def password_label_for(user)
    has_password = user.crypted_password.present?
    @label = has_password ? 'Change password' : 'Create password'
    @placeholder = has_password ? 'Type new password to change it' : nil
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def display_name_for(user)
    user.name.blank? ? user.username : user.name
  end
end

app/views/users/edit.html.haml
= render 'shared/error_messages', object: @user
.container-fluid
  %h1= display_name_for @user
  .row
    .col-sm-3.col-md-2
      .thumbnail.no-border
        = image_tag 'http://placehold.io/300/300.jpeg'
    .col-sm-4.col-md-3
      = form_for @user do |f|
        .form-group
          = f.label :name
          = f.text_field :name, class: 'form-control'
        .form-group
          = f.label :username
          = f.text_field :username, class: 'form-control'
        .form-group
          = f.label :email
          = f.email_field :email, class: 'form-control'
        .form-group
          = f.label :password, @label
          = f.password_field :password, {placeholder: @placeholder, class: 'form-control'}
          .text-right.text-muted
            = label_tag :show_password do
              = check_box_tag 'show_password', 'yes', false
              %small
                Show password
        = f.submit 'Save profile', class: 'btn btn-success'

app/views/users/new.html.haml
= render 'shared/error_messages', object: @user
.container
  #wrapper
    .panel.panel-default
      .panel-body
        = form_for @user, html: { class: 'form-horizontal' } do |f|
          .col-xs-12
            .form-group
              .input-group
                %span.input-group-addon
                  = fa_icon 'at'
                = f.email_field :email, { class: 'form-control', placeholder: 'Email', autocomplete: 'off' }
          .col-xs-12
            .form-group
              .input-group
                %span.input-group-addon
                  = fa_icon 'user'
                = f.text_field :username, { class: 'form-control', placeholder: 'Username', autocomplete: 'off', autocapitalize: 'off' }
          .col-xs-12
            .form-group
              .input-group
                %span.input-group-addon
                  = fa_icon 'lock'
                = f.password_field :password, { class: 'form-control', placeholder: 'Password' }
              .text-right.text-muted
                = label_tag :show_password do
                  = check_box_tag 'show_password', 'yes', false
                  %small
                    Show password
          .col-xs-12
            .form-group
              = submit_tag 'Join flickflow', class: 'btn btn-primary btn-block'
        .col-xs-12
          %hr/
          .text-center
            %p Or join with your social profile
            = render 'shared/oauth_links'
        .col-xs-12
          %hr/
          .text-center
            = link_to 'Sign in to flickflow', signin_path