config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  namespace :admin do
    get 'fetch' => 'movies#fetch', as: 'fetch'
    resources :movies, :people, :lists, :users
    root 'dashboard#index'
  end

  namespace :api do
    resources :movies, only: [:index, :show] do
      with_options only: :index do |list_only|
        list_only.resources :alternative_titles
        list_only.resources :credits
        list_only.resources :critic_reviews
        list_only.resources :genres
        list_only.resources :keywords
        list_only.resources :posters
        list_only.resources :recommended_movies
        list_only.resources :releases
        list_only.resources :trivia
      end
    end

    resources :people, only: :show do
      resources :movie_credits, only: :index
    end

    resources :genres, only: [:index, :show] do
      resources :movies, only: :index
    end

    resources :keywords, only: [:index, :show] do
      resources :movies, only: :index
    end

    resources :users do
      resources :lists, only: :show
    end

    resources :lists do
      post 'toggle', on: :member
    end
  end

  resources :movies, only: [:index, :show]
  resources :users, only: [:new, :create, :edit, :update]
  resources :sessions, only: [:new, :create, :destroy]

  get 'watchlist' => 'lists#show', id: 'watchlist', as: :watchlist
  get 'watched'   => 'lists#show', id: 'watched', as: :watched
  get 'favorites' => 'lists#show', id: 'favorites', as: :favorites

  get 'sign-in' => 'sessions#new', as: :signin
  delete 'sign-out' => 'sessions#destroy', as: :signout
  get 'join' => 'users#new', as: :join

  post 'oauth/callback' => 'oauths#callback'
  get 'oauth/callback' => 'oauths#callback'
  get 'oauth/:provider' => 'oauths#oauth',  as: :auth_at_provider

  get 'profile' => 'users#edit', as: :profile
  post 'profile' => 'users#update'

  mount Sidekiq::Web, at: '/sidekiq'

  root 'movies#index'
end

app/views/shared/_error_messages.html.haml
- if object.errors.any?
  .container-fluid.system-messages
    .row
      .col-sm-6.col-sm-offset-3
        .alert.fade.in.alert-danger.alert-dismissable
          %button.close{type: 'button', data: { dismiss: 'alert' }}
            %span{aria: { hidden: 'true' }}
              = fa_icon 'times'
          %ul#error-messages
            - object.errors.full_messages.each do |msg|
              = content_tag :li, msg if msg.is_a?(String)

app/views/shared/_flash_messages.html.haml
- if flash.any?
  .container-fluid.system-messages
    - flash.each do |msg_type, msg|
      .row
        .col-sm-6.col-sm-offset-3
          %div.alert.fade.in.alert-dismissable{class: "#{bootstrap_class_for(msg_type)}"}
            %button.close{type: 'button', data: { dismiss: 'alert' }}
              %span{aria: { hidden: 'true' }}
                = fa_icon 'times'
            %p= msg

app/views/shared/_navbar.html.haml
.navbar.navbar-inverse.navbar-static-top
  .container-fluid
    %ul.nav.navbar-nav
      %li.dropdown
        %a.dropdown-toggle{href: '#', data: {toggle: 'dropdown'}}
          = fa_icon 'bars', text: 'Discover'
          %span= fa_icon 'angle-down'
        %ul.dropdown-menu
          %li.visible-xs= link_to 'Popular Now', root_path
          %li= link_to 'Coming Soon', '#'
          %li= link_to 'By Genre', '#'
          %li= link_to 'Spotlight', '#'
          %li= link_to 'Top 1000', '#'
          %li= link_to 'People', '#'
      %li.hidden-xs= link_to 'Popular Now', root_path
    %ul.nav.navbar-nav.navbar-right
      %li= link_to fa_icon('star', text: 'Watchlist'), watchlist_path
      %li.hidden-xs= link_to fa_icon('check-square-o', text: 'Watched'), watched_path
      %li.hidden-xs= link_to fa_icon('heart', text: 'Favorites'), favorites_path
      %li.dropdown
        = link_to '#', class: 'dropdown-toggle', data: {toggle: 'dropdown'} do
          = fa_icon 'user'
          %span.hidden-xs= current_user.name
          %span= fa_icon 'angle-down'
        %ul.dropdown-menu
          %li.visible-xs= link_to fa_icon('check-square-o', text: 'Watched'), watched_path
          %li.visible-xs= link_to fa_icon('heart', text: 'Favorites'), favorites_path
          %li.divider.visible-xs
          %li= link_to fa_icon('cog', text: 'Profile'), profile_path
          %li= link_to fa_icon('sign-out', text: 'Sign Out'), signout_path, method: :delete

app/views/shared/_oauth_links.html.haml
= link_to fa_icon('facebook-square 3x'), auth_at_provider_path(provider: :facebook), class: 'icon-social icon-facebook'
= link_to fa_icon('twitter 3x'), auth_at_provider_path(provider: :twitter), class: 'icon-social icon-twitter'
= link_to fa_icon('google-plus-square 3x'), auth_at_provider_path(provider: :google), class: 'icon-social icon-google'
= link_to fa_icon('vk 3x'), auth_at_provider_path(provider: :vk), class: 'icon-social icon-vk'

app/views/shared/_sidebar.html.haml
.col-md-2.col-sm-3.hidden-xs
  #sidebar
    .list-group
      - @user_lists.each do |list|
        = link_to '#', class: 'list-group-item' do
          = list.name
          %span.badge.badge-default.pull-right= list.list_entries.size
    .list-group
      %a.list-group-item{href: '#'}
        Generes
      %a.list-group-item{href: '#'}
        Popular Now
      %a.list-group-item{href: '#'}
        Coming Soon
      %a.list-group-item{href: '#'}
        Spotlight
      %a.list-group-item{href: '#'}
        Top 1000
      %a.list-group-item{href: '#'}
        People
    - if current_user
      .list-group
        = link_to profile_path, class: 'list-group-item' do
          = fa_icon 'user', text: 'Profile'
        = link_to '#', class: 'list-group-item' do
          = fa_icon 'cog', text: 'Settings'
        = link_to signout_path, class: 'list-group-item', method: :delete do
          = fa_icon 'sign-out', text: 'Sign Out'

app/views/shared/_user_dropdown.html.haml
- if current_user
  %ul.nav.navbar-nav.navbar-right
    %li.dropdown
      %a.dropdown-toggle{href: '#', data: {toggle: 'dropdown'}}
        = fa_icon 'user'
        %span.hidden-sm= display_name_for current_user
        %span.caret
      %ul.dropdown-menu{role: 'menu'}
        %li= link_to fa_icon('user', text: 'Profile'), profile_path
        %li= link_to fa_icon('cog', text: 'Settings'), '#'
        %li.divider
        %li= link_to fa_icon('sign-out', text: 'Sign Out'), signout_path, method: :delete